### PR TITLE
Support for Unreal Engine 5

### PR DESCRIPTION
**Pull request by mehmetcanakbay**
Added support for Unreal Engine 5. 
Tested on Unreal Engine ver. 5.2 and it's working without any problems.

show-image

### CODE REVIEW

**Comment by zfw1226** [comment]
@mehmetcanakbay Great job! Thank you for your valuable contribution to the UnrealCV project! I have created a new branch (5.2) and merged your new update into this branch.

Your efforts to ensure compatibility with Unreal Engine 5.2 are greatly appreciated. We are grateful for the time and dedication you've put into this project, and we're excited to see how the integration of these new features will enhance the capabilities of UnrealCV.

We encourage you to continue engaging with our community and look forward to any future contributions you might have. Your expertise and passion for open-source development are truly inspiring. Once again, thank you for your outstanding work.

**Comment by mehmetcanakbay** [comment]
@zfw1226 Thank you for your hard work as well, your words mean a lot to me. 

Since you merged it in a different branch, I will be closing this PR.

**Comment by Marmiya** [comment]
@mehmetcanakbay Thank u for ur work! I cloneed your branch and it can be compiled in my env: Win11 and UE5.2.
However, I find it only can be used in the console in Editor. I find there are some warnings:
image
**FTcpSocketBuilder: Failed to create the socket FTcpListener server as configured
LogUnrealCV: Warning: Cannot start listening on port 9000, Port might be in use
LogUnrealCV: Warning: Failed to start network server**
Hence I cannot get the results remotely.  I had checked the port's status and my firewall but it's not work. I can use the original unrealcv. Could u give me some suggestions？

**Comment by Marmiya** [comment]
@mehmetcanakbay Great! I just tested the new one and it works well. Btw, I uncommented the _.AsReusable()_ and it also works. Thank for ur efforts!

**Comment by FelixHSS** [comment]
How do we build the new release? Thanks

**Comment by KaiMJ** [comment]
python build.py --UE4 /path/to-engine

results in 

`
/path/to-engine/unrealcv/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/UnrealCV.Build.cs(79,6): error CS0103: The name 'bFasterWithoutUnity' does not exist in the current context
`

Any solutions?

**Comment by VV-A-VV** [comment]
> @Marmiya Hello, thank you for bringing this to my attention.
> 
> I did some changes on my [fork](https://github.com/mehmetcanakbay/unrealcvUE5), can you clone my fork and test it? I do not know your setup so I cannot test this potential fix. It should be working properly now though.
> 
> Please tell us if it works so we can merge it into the branch here.

It seems to be a unstable fix, I have tried dozens of times, and about 60% of the attempts to start TcpServer on Windows fail. I haven't found the cause of the problem yet.

**Pull request closed without merging**
